name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Run linter
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      # Run tests
      - name: Run tests
        run: go test ./...

      # Build Docker image
      - name: Build Docker image
        run: docker build -t golang-ci-cd .

      # Push Docker image (if needed)
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        if: github.ref == 'refs/heads/main'
        run: docker tag golang-ci-cd ${{ secrets.DOCKER_USERNAME }}/golang-ci-cd:latest && \
             docker push ${{ secrets.DOCKER_USERNAME }}/golang-ci-cd:latest
